### ISSUE TITLE
Is there a way to remove the hash from the URL?

### ISSUE THREAD

**Issue by pathetix** [DizzyZane/lightbox#1]
When you click on a link that calls the lightbox, the url shows something like:
index.html#lightbox1-l

Possible to remove the hash?

**Comment by DizzyZane** [comment]
I'm working on one that uses `label`s and `input`s, however, you can
just add `input:checked+[lightbox]` with

    <input type="radio" name="lightbox" id="lightbox-l"><lightbox
lightbox="left"></lightbox>
    <label for="lightbox-l-input">Open lightbox</label>

Besides, it relinquishes the users control of the lightbox, meaning
that hardware, software and other "Back" buttons have no effect on the
lightbox, instead, going back a page.

-- 
*Dizzy_Zane*

**Comment by DizzyZane** [comment]
I'm working on one that uses `label`s and `input`s, however, you can
just add `input:checked+[lightbox]`

```
<input type="radio" name="lightbox" id="lightbox-l"><lightbox lightbox="left"></lightbox>
<label for="lightbox-l-input">Open lightbox</label>
```

Besides, it relinquishes the users control of the lightbox, meaning
that hardware, software and other "Back" buttons have no effect on the
lightbox, instead, going back a page.

**Comment by pathetix** [comment]
Oh great, where exactly can I insert the rule 'input:checked+[lightbox]' in the lightbox.css file?

**Comment by DizzyZane** [comment]
Everywhere where it says `[lightbox]:target`. You'll also have to add in the syntax.

I'll add it.

**Comment by pathetix** [comment]
Great it works.
Perhaps you want to rephrase how to do the label+input method in the readme. 

Thanks a lot!
