### ISSUE TITLE
Cannot check if the radio button is checked via jquery

### ISSUE THREAD

**Issue by pathetix** [DizzyZane/lightbox#2]
I am trying to do something if the lightbox is opened, so I use jQuery to check if the radio button is checked.
However, it does not return any value. Is this normal?

``` javascript
if ($("#lightbox_lbl").prop("checked")) {
    console.log('Lightbox is Visible');
}
```

**Comment by DizzyZane** [comment]
I believe it is seen as indeterminate until one of the values are checked, so just add the `checked` attribute to the `remove_lightbox` radio, like so:

`<input name="lightbox" type="radio" id="remove_lightbox" checked>`

Also, if you put it at the very start of the document (`body>#remove_lightbox:not(:checked)~* (css selector)`) you can check the styling of the element.

Also, I have absolutely no clue how to use jQuery and little knowledge of Javascript. So I'm just taking a shot in the dark with this one.

**Comment by pathetix** [comment]
Ah okay sorry, there needs to be an event handler for it to be detected.
I came up with this and it works:

``` javascript
$('input:radio#lightbox_lbl').change(function(){
    if($(this).prop('checked')){
        console.log('Lightbox is Visible!');
    }
});
```

Thanks again!

**Comment by DizzyZane** [comment]
You may want to use `input:radio#remove_lightbox` and log `lightbox is visible` when it is unchecked.

:)
